FakeMessenger\Conversation\Domain\Entity\Message:
  type: entity
  repositoryClass: FakeMessenger\Conversation\Infrastructure\Doctrine\ORM\Repository\MessageRepository
  table: messages
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    sendDate:
      type: datetime
    content:
     type: string
  manyToOne:
    conversation:
      targetEntity: FakeMessenger\Conversation\Domain\Entity\Conversation
      inversedBy: messages
      joinColumn:
        name: conversation_id
        referencedColumnName: id
        nullable: false
