#api_fake_messenger:
#    resource: "@FakeMessengerBundle/Controller/ApiConversationController.php"
#    type: annotation

fake_messenger:
    resource: "@FakeMessengerBundle/Controller/"
    type:     annotation
    prefix:   /
